version: '3.7'

services:
  auth:
    build: ./disastergram-auth
    ports:
    - "5000:5000"
    depends_on:
      - auth-db

  # https://hub.docker.com/_/postgres
  auth-db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: disastergram
    volumes:
      - auth-data:/var/lib/postgresql/

  api-frontend:
    build: ./disastergram-web
    volumes:
     - './disastergram-web:/usr/src/app'
     - '/usr/src/app/node_modules'
    ports:
     - '3000:3000'
    environment:
     - NODE_ENV=development

  reverse-proxy:
    image: nginx:1.16
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 0.0.0.0:80:80
    depends_on:
      - auth
      - api-frontend


volumes:
  auth-data: